src/OrderBundle/Entity/Cart.php
<?php

namespace OrderBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Cart
 *
 * @ORM\Table(name="cart")
 * @ORM\Entity(repositoryClass="OrderBundle\Repository\CartRepository")
 */
class Cart
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="date", type="datetime", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(name="status", type="smallint")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", cascade={"persist"})
     */
    private $owner;

    /**
     * @ORM\ManyToMany(targetEntity="RestaurantBundle\Entity\Recipe", cascade={"persist"})
     */
    private $recipes;

    /**
     * @ORM\ManyToOne(targetEntity="RestaurantBundle\Entity\Restaurant", cascade={"persist"})
     */
    private $restaurant;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->recipes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set owner.
     *
     * @param \UserBundle\Entity\User|null $owner
     *
     * @return Cart
     */
    public function setOwner(\UserBundle\Entity\User $owner = null)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Get owner.
     *
     * @return \UserBundle\Entity\User|null
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Add recipe.
     *
     * @param \RestaurantBundle\Entity\Recipe $recipe
     *
     * @return Cart
     */
    public function addRecipe(\RestaurantBundle\Entity\Recipe $recipe)
    {
        $this->recipes[] = $recipe;

        return $this;
    }

    /**
     * Remove recipe.
     *
     * @param \RestaurantBundle\Entity\Recipe $recipe
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeRecipe(\RestaurantBundle\Entity\Recipe $recipe)
    {
        return $this->recipes->removeElement($recipe);
    }

    /**
     * Get recipes.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRecipes()
    {
        return $this->recipes;
    }

    /**
     * Set restaurant.
     *
     * @param \RestaurantBundle\Entity\Restaurant|null $restaurant
     *
     * @return Cart
     */
    public function setRestaurant(\RestaurantBundle\Entity\Restaurant $restaurant = null)
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    /**
     * Get restaurant.
     *
     * @return \RestaurantBundle\Entity\Restaurant|null
     */
    public function getRestaurant()
    {
        return $this->restaurant;
    }

    /**
     * Set date.
     *
     * @param \DateTime|null $date
     *
     * @return Cart
     */
    public function setDate($date = null)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date.
     *
     * @return \DateTime|null
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set status.
     *
     * @param int $status
     *
     * @return Cart
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Return the total cost of the order.
     *
     * @return int
     */
    public function getTotalPrice()
    {
        $total = 0;

        foreach ($this->recipes as $recipe) {
            $total += $recipe->getPrice();
        }

        return $total;
    }
}

src/OrderBundle/Resources/views/checkout.html.twig
{% extends '@BigFood/layout.html.twig' %}

{% block title %}
    Checkout
{% endblock %}

{% block body %}
    <h1 class="text-center text-warning">PROCEED TO CHECKOUT</h1>
    <br>
    {% if cart is defined and cart is not empty %}
    <h3 class="text-center text-warning">{{ cart.restaurant.name|upper }}</h3>
        <div class="table-responsive">
            <table class="table text-left">
                <tr class="thead-light">
                    <th colspan="4">Your order</th>
                </tr>
                {% for recipe in cart.recipes %}
                    <tr class="table-hover">
                        <td>{{ recipe.name }}</td>
                        <td class="font-italic text-secondary">{{ recipe.description }}</td>
                        <td class="font-italic text-secondary">{{ recipe.price }} €</td>
                        <td><a href="{{ path('remove_from_cart', {'recipe': recipe.id, 'cart': cart.id}) }}" class="btn btn-warning btn-block" title="Remove from cart"><i class="fas fa-times"></i></a></td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="2" class="font-weight-bold">TOTAL :</td>
                    <td class="font-weight-bold">{{ cart.totalPrice }} €</td>
                    <td><a href="{{ path('proceed_checkout', {'id': cart.id}) }}" class="btn btn-warning btn-block" title="Order"><i class="fas fa-cart-arrow-down"></i></a></td>
                </tr>
            </table>
        </div>
    {% else %}
        <div class="text-center">
            <span class="alert alert-warning">Your cart is empty !</span>
        </div>
    {% endif %}
{% endblock %}

src/OrderBundle/Resources/views/manage_orders.html.twig
{% extends '@BigFood/layout.html.twig' %}

{% block title %}
    Manage Orders
{% endblock %}

{% block body %}
    <h1 class="text-center text-warning text-uppercase">Manage Orders to {{ restaurant.name }}</h1>
    <br>
    {% if carts is not empty %}
        <div class="table-responsive">
            <table class="table table-hover">
                <tr class="thead-light">
                    <th>Date</th>
                    <th>Username</th>
                    <th>Order</th>
                    <th>Price</th>
                    <th>Status</th>
                </tr>
                {% for cart in carts %}
                    <tr>
                        <td>{{ cart.date|date("d/m/Y - H:i") }}</td>
                        <td>{{ cart.owner.username }}</td>
                        <td>
                            <ul class="list-group">
                            {% for recipe in cart.recipes %}
                                <li>{{ recipe.name }}</li>
                            {% endfor %}
                            </ul>
                        </td>
                        <td>{{ cart.totalPrice }} € </td>
                        <td><a class="btn btn-warning" href="{{ path('archive_order', {'id': cart.id}) }}" title="Done"><i class="fas fa-check"></i></a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <div class="text-center">
            <span class="alert alert-warning">No pending orders</span>
        </div>
    {% endif %}
{% endblock %}